# Generated by Django 5.1.1 on 2024-10-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirepost",
            name="phone",
            field=models.CharField(default="0000000000", max_length=15),
        ),
    ]
